version: '2'
services:
  gogs:
    image: "gogs/gogs:latest"
    container_name: "gogs"
    restart: always
    ports:
      - "8022:22"
      - "3000:3000"
    volumes:
      - ./docker/gogs/data:/data