version: '2'
services:
  gogs:
    image: "gogs/gogs:latest"
    container_name: "gogs"
    restart: always
    ports:
      - "8022:22"
      - "3000:3000"
    volumes:
      - ./docker/gogs/data:/data
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gogs
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: gogs
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf:/etc/mysql/conf.d
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - type: bind
    source: /home/yangxufeng/yxf.gitlab/docker/jenkins/home
    target: /var/jenkins_home